# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Govpn < Formula
  desc "govpn helps you easily and quickly provision EC2 with terraform and consume vpn service on your mobile or computer via outline application."
  homepage ""
  version "0.1.1-SNAPSHOT-9cc83e1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ghdwlsgur/govpn/releases/download/v0.1.1/govpn_0.1.1-SNAPSHOT-9cc83e1_Darwin_arm64.tar.gz"
      sha256 "9956a2fb28c16c7c9761684fbaea553e8cbff02dbf45a4ae649b1026eef9c5d1"

      def install
        bin.install "govpn"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ghdwlsgur/govpn/releases/download/v0.1.1/govpn_0.1.1-SNAPSHOT-9cc83e1_Darwin_x86_64.tar.gz"
      sha256 "7ceb7689d1445f174ad6c4628efa98e52ea5705c51e16d9315728d2a478e2ad8"

      def install
        bin.install "govpn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ghdwlsgur/govpn/releases/download/v0.1.1/govpn_0.1.1-SNAPSHOT-9cc83e1_Linux_arm64.tar.gz"
      sha256 "2f4b6264c9c6a0753b40f8a4d7bfb8ca31e04f31d7c2809d3c6da05a2043c4eb"

      def install
        bin.install "govpn"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ghdwlsgur/govpn/releases/download/v0.1.1/govpn_0.1.1-SNAPSHOT-9cc83e1_Linux_x86_64.tar.gz"
      sha256 "3ff752cb747ef574d0a987f8ef7b317f2c3d07d4644dbfeb6fdb8d2ebb4e957d"

      def install
        bin.install "govpn"
      end
    end
  end
end
