# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Govpn < Formula
  desc "govpn helps you easily and quickly provision EC2 with terraform and consume vpn service on your mobile or computer via outline application."
  homepage ""
  version "0.1.8"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ghdwlsgur/govpn/releases/download/v0.1.8/govpn_0.1.8_Darwin_arm64.tar.gz"
      sha256 "f38921a32937d37bc83920af771a301d245693010bd03091baa4fd0aeee5a75b"

      def install
        bin.install "govpn"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ghdwlsgur/govpn/releases/download/v0.1.8/govpn_0.1.8_Darwin_x86_64.tar.gz"
      sha256 "5efa8c523a9fc52947adf9312578db1813aa2f29c20d6302407199d06b517dd6"

      def install
        bin.install "govpn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ghdwlsgur/govpn/releases/download/v0.1.8/govpn_0.1.8_Linux_arm64.tar.gz"
      sha256 "cf881f58c0bde668d35e6fc50332f6bef10008daca90eb28f9ba1c258c5228e6"

      def install
        bin.install "govpn"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ghdwlsgur/govpn/releases/download/v0.1.8/govpn_0.1.8_Linux_x86_64.tar.gz"
      sha256 "20006a4dd65fa5d309473d1902e5a83c0fb65eff3033bbf5fc64b8a95473d945"

      def install
        bin.install "govpn"
      end
    end
  end
end
